export { default as AboutMe } from "./AboutMe";
export { default as AddPhotos } from "./AddPhotos";
export { default as Admin } from "./Admin";
export { default as Contact } from "./Contact";
export { default as EditInfo } from "./EditInfo";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as LightboxTest } from "./LightboxTest";
export { default as Loading } from "./Loading";
export { default as Login } from "./Login";
export { default as Main } from "./Main";
export { default as MyWork } from "./MyWork";
export { default as Navbar } from "./Navbar";
export { default as NewAbout } from "./NewAbout";
export { default as NewTest } from "./NewTest";
export { default as Register } from "./Register";
export { default as UploadImages } from "./UploadImages";
export { default as UserCard } from "./UserCard"
export { default as UserList } from "./UserList";
